version: "1.5.0+{build}"

environment:
    matrix:
        - job_name: VS 2019 x64, Qt 6.2
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CMAKE_GENERATOR: Visual Studio 16 2019
          QT_DIR: C:\Qt\6.2\msvc2019_64
          VCVARS_COMMANDLINE: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
          CMAKE_INSTALL_PATH: 'C:\Program Files\CMake'

        - job_name: VS 2019 x64, Qt 5.15
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CMAKE_GENERATOR: Visual Studio 16 2019
          QT_DIR: C:\Qt\5.15\msvc2019_64
          VCVARS_COMMANDLINE: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
          CMAKE_INSTALL_PATH: 'C:\Program Files\CMake'

        - job_name: VS 2017 x64, Qt 5.12
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CMAKE_GENERATOR: Visual Studio 15 2017 Win64
          QT_DIR: C:\Qt\5.12\msvc2017_64
          VCVARS_COMMANDLINE: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
          CMAKE_INSTALL_PATH: 'C:\Program Files (x86)\CMake'

        - job_name: VS 2015 x86, Qt 5.9
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_GENERATOR: Visual Studio 14 2015
          QT_DIR: C:\Qt\5.9\msvc2015
          VCVARS_COMMANDLINE: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
          CMAKE_INSTALL_PATH: 'C:\Program Files (x86)\CMake'

        - job_name: VS 2015 x86, Qt 5.6
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_GENERATOR: Visual Studio 14 2015
          QT_DIR: C:\Qt\5.6\msvc2015
          VCVARS_COMMANDLINE: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
          CMAKE_INSTALL_PATH: 'C:\Program Files (x86)\CMake'

cache:
    - C:\.hunter -> .appveyor.yml, **\CMakeLists.txt, **\*.cmake

before_build:
    - call %VCVARS_COMMANDLINE%
    - set Path=%QT_DIR%\bin;%Path%
    - set QT_QPA_PLATFORM_PLUGIN_PATH=%QT_DIR%\plugins
    - cd tests
    - mkdir _build
    - cd _build
    - cmake -G "%CMAKE_GENERATOR%" ..

build:
    project: tests\_build\ALL_BUILD.vcxproj


test_script:
    - '"%CMAKE_INSTALL_PATH%\bin\ctest.exe" --output-on-failure -C Debug'
